### ISSUE TITLE
[Feat] 애플로그인 구현, 로그인 뷰 Hi-Fi로 수정

### ISSUE THREAD

**Issue by LeeChangHyeong** [TeamGoodGood/RelayNovel_iOS#12]
**Issue : Feature**
- 애플 로그인을 구현해야 합니다
- figma의 hi-fi와 동일하게 ui를 만들어야 합니다

**Description**
- 애플 로그인 버튼 클릭 시 모달로 로그인 창 올라옵니다
- 로그인 완료시 로그인 한 사람의 이름, 이메일을 확인 할 수 있습니다

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 애플로그인 구현
- [x] 되는지 확인
- [x] hi-fi와 ui동일

**Comment by JaewoongLee-swift** [comment]
애플로그인 구현이 어느정도까지 구현되는지와 구현되는 View의 위치 등의 작업사항을 적어주시면 참고할 때 용이할것 같습니다.

**Comment by LeeChangHyeong** [comment]
> 애플로그인 구현이 어느정도까지 구현되는지와 구현되는 View의 위치 등의 작업사항을 적어주시면 참고할 때 용이할것 같습니다.

반영하겠습니다 ~
